apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-checker
  template:
    metadata:
      labels:
        app: url-checker
    spec:
      containers:
      - name: url-checker
        image: vivekb1313/dev:latest
        ports:
        - containerPort: 8080
